// ISO 4217 主要通貨リスト（コード・英語名・記号候補）
// 為替レートAPI（open.er-api.com）が対応する通貨とほぼ一致
const CURRENCIES = [
  { code: "JPY", name: "日本円", symbols: ["¥", "円", "JPY"] },
  { code: "USD", name: "米ドル", symbols: ["$", "US$", "USD"] },
  { code: "EUR", name: "ユーロ", symbols: ["€", "EUR"] },
  { code: "GBP", name: "英ポンド", symbols: ["£", "GBP"] },
  { code: "CNY", name: "中国元", symbols: ["¥", "元", "RMB", "CNY"] },
  { code: "KRW", name: "韓国ウォン", symbols: ["₩", "KRW"] },
  { code: "AUD", name: "豪ドル", symbols: ["A$", "AUD"] },
  { code: "CAD", name: "加ドル", symbols: ["C$", "CAD"] },
  { code: "CHF", name: "スイスフラン", symbols: ["CHF", "Fr"] },
  { code: "HKD", name: "香港ドル", symbols: ["HK$", "HKD"] },
  { code: "SGD", name: "シンガポールドル", symbols: ["S$", "SGD"] },
  { code: "THB", name: "タイバーツ", symbols: ["฿", "THB"] },
  { code: "TWD", name: "台湾ドル", symbols: ["NT$", "TWD"] },
  { code: "PHP", name: "フィリピンペソ", symbols: ["₱", "PHP"] },
  { code: "VND", name: "ベトナムドン", symbols: ["₫", "VND"] },
  { code: "IDR", name: "インドネシアルピア", symbols: ["Rp", "IDR"] },
  { code: "MYR", name: "マレーシアリンギット", symbols: ["RM", "MYR"] },
  { code: "INR", name: "インドルピー", symbols: ["₹", "INR"] },
  { code: "NZD", name: "NZドル", symbols: ["NZ$", "NZD"] },
  { code: "MXN", name: "メキシコペソ", symbols: ["MX$", "MXN"] },
  { code: "BRL", name: "ブラジルレアル", symbols: ["R$", "BRL"] },
  { code: "ZAR", name: "南アフリカランド", symbols: ["R", "ZAR"] },
  { code: "TRY", name: "トルコリラ", symbols: ["₺", "TRY"] },
  { code: "RUB", name: "ロシアルーブル", symbols: ["₽", "RUB"] },
  { code: "SEK", name: "スウェーデンクローナ", symbols: ["kr", "SEK"] },
  { code: "NOK", name: "ノルウェークローネ", symbols: ["kr", "NOK"] },
  { code: "DKK", name: "デンマーククローネ", symbols: ["kr", "DKK"] },
  { code: "PLN", name: "ポーランドズロチ", symbols: ["zł", "PLN"] },
  { code: "CZK", name: "チェココルナ", symbols: ["Kč", "CZK"] },
  { code: "HUF", name: "ハンガリーフォリント", symbols: ["Ft", "HUF"] },
  { code: "ILS", name: "イスラエルシェケル", symbols: ["₪", "ILS"] },
  { code: "AED", name: "UAEディルハム", symbols: ["د.إ", "AED"] },
  { code: "SAR", name: "サウジリヤル", symbols: ["﷼", "SAR"] },
  { code: "QAR", name: "カタールリヤル", symbols: ["QAR"] },
  { code: "KWD", name: "クウェートディナール", symbols: ["KWD"] },
  { code: "BHD", name: "バーレーンディナール", symbols: ["BHD"] },
  { code: "OMR", name: "オマーンリヤル", symbols: ["OMR"] },
  { code: "JOD", name: "ヨルダンディナール", symbols: ["JOD"] },
  { code: "EGP", name: "エジプトポンド", symbols: ["E£", "EGP"] },
  { code: "PKR", name: "パキスタンルピー", symbols: ["₨", "PKR"] },
  { code: "BDT", name: "バングラデシュタカ", symbols: ["৳", "BDT"] },
  { code: "LKR", name: "スリランカルピー", symbols: ["Rs", "LKR"] },
  { code: "NPR", name: "ネパールルピー", symbols: ["Rs", "NPR"] },
  { code: "MMK", name: "ミャンマーチャット", symbols: ["K", "MMK"] },
  { code: "KHR", name: "カンボジアリエル", symbols: ["៛", "KHR"] },
  { code: "LAK", name: "ラオスキープ", symbols: ["₭", "LAK"] },
  { code: "MNT", name: "モンゴルトゥグルグ", symbols: ["₮", "MNT"] },
  { code: "KZT", name: "カザフスタンテンゲ", symbols: ["₸", "KZT"] },
  { code: "UZS", name: "ウズベキスタンソム", symbols: ["UZS"] },
  { code: "UAH", name: "ウクライナフリヴニャ", symbols: ["₴", "UAH"] },
  { code: "RON", name: "ルーマニアレウ", symbols: ["lei", "RON"] },
  { code: "BGN", name: "ブルガリアレフ", symbols: ["лв", "BGN"] },
  { code: "HRK", name: "クロアチアクーナ", symbols: ["kn", "HRK"] },
  { code: "ISK", name: "アイスランドクローナ", symbols: ["kr", "ISK"] },
  { code: "RSD", name: "セルビアディナール", symbols: ["дин", "RSD"] },
  { code: "GEL", name: "ジョージアラリ", symbols: ["₾", "GEL"] },
  { code: "AMD", name: "アルメニアドラム", symbols: ["֏", "AMD"] },
  { code: "AZN", name: "アゼルバイジャンマナト", symbols: ["₼", "AZN"] },
  { code: "BYN", name: "ベラルーシルーブル", symbols: ["Br", "BYN"] },
  { code: "MDL", name: "モルドバレウ", symbols: ["MDL"] },
  { code: "ALL", name: "アルバニアレク", symbols: ["L", "ALL"] },
  { code: "MKD", name: "北マケドニアデナル", symbols: ["ден", "MKD"] },
  { code: "BAM", name: "ボスニア兌換マルク", symbols: ["KM", "BAM"] },
  { code: "COP", name: "コロンビアペソ", symbols: ["COL$", "COP"] },
  { code: "ARS", name: "アルゼンチンペソ", symbols: ["AR$", "ARS"] },
  { code: "CLP", name: "チリペソ", symbols: ["CL$", "CLP"] },
  { code: "PEN", name: "ペルーソル", symbols: ["S/", "PEN"] },
  { code: "UYU", name: "ウルグアイペソ", symbols: ["$U", "UYU"] },
  { code: "BOB", name: "ボリビアーノ", symbols: ["Bs", "BOB"] },
  { code: "PYG", name: "パラグアイグアラニ", symbols: ["₲", "PYG"] },
  { code: "GTQ", name: "グアテマラケツァル", symbols: ["Q", "GTQ"] },
  { code: "CRC", name: "コスタリカコロン", symbols: ["₡", "CRC"] },
  { code: "DOP", name: "ドミニカペソ", symbols: ["RD$", "DOP"] },
  { code: "PAB", name: "パナマバルボア", symbols: ["B/.", "PAB"] },
  { code: "HNL", name: "ホンジュラスレンピラ", symbols: ["L", "HNL"] },
  { code: "NIO", name: "ニカラグアコルドバ", symbols: ["C$", "NIO"] },
  { code: "JMD", name: "ジャマイカドル", symbols: ["J$", "JMD"] },
  { code: "TTD", name: "トリニダードトバゴドル", symbols: ["TT$", "TTD"] },
  { code: "BSD", name: "バハマドル", symbols: ["B$", "BSD"] },
  { code: "BBD", name: "バルバドスドル", symbols: ["Bds$", "BBD"] },
  { code: "XCD", name: "東カリブドル", symbols: ["EC$", "XCD"] },
  { code: "BZD", name: "ベリーズドル", symbols: ["BZ$", "BZD"] },
  { code: "FJD", name: "フィジードル", symbols: ["FJ$", "FJD"] },
  { code: "PGK", name: "パプアニューギニアキナ", symbols: ["K", "PGK"] },
  { code: "WST", name: "サモアタラ", symbols: ["WS$", "WST"] },
  { code: "TOP", name: "トンガパアンガ", symbols: ["T$", "TOP"] },
  { code: "SBD", name: "ソロモン諸島ドル", symbols: ["SI$", "SBD"] },
  { code: "VUV", name: "バヌアツバツ", symbols: ["VT", "VUV"] },
  { code: "XPF", name: "CFPフラン", symbols: ["₣", "XPF"] },
  { code: "NGN", name: "ナイジェリアナイラ", symbols: ["₦", "NGN"] },
  { code: "GHS", name: "ガーナセディ", symbols: ["₵", "GHS"] },
  { code: "KES", name: "ケニアシリング", symbols: ["KSh", "KES"] },
  { code: "TZS", name: "タンザニアシリング", symbols: ["TSh", "TZS"] },
  { code: "UGX", name: "ウガンダシリング", symbols: ["USh", "UGX"] },
  { code: "ETB", name: "エチオピアブル", symbols: ["Br", "ETB"] },
  { code: "MAD", name: "モロッコディルハム", symbols: ["MAD", "DH"] },
  { code: "DZD", name: "アルジェリアディナール", symbols: ["DA", "DZD"] },
  { code: "TND", name: "チュニジアディナール", symbols: ["DT", "TND"] },
  { code: "LYD", name: "リビアディナール", symbols: ["LD", "LYD"] },
  { code: "XOF", name: "西アフリカCFAフラン", symbols: ["CFA", "XOF"] },
  { code: "XAF", name: "中央アフリカCFAフラン", symbols: ["FCFA", "XAF"] },
  { code: "ZMW", name: "ザンビアクワチャ", symbols: ["ZK", "ZMW"] },
  { code: "MZN", name: "モザンビークメティカル", symbols: ["MT", "MZN"] },
  { code: "BWP", name: "ボツワナプラ", symbols: ["P", "BWP"] },
  { code: "NAD", name: "ナミビアドル", symbols: ["N$", "NAD"] },
  { code: "MUR", name: "モーリシャスルピー", symbols: ["₨", "MUR"] },
  { code: "MGA", name: "マダガスカルアリアリ", symbols: ["Ar", "MGA"] },
  { code: "XDR", name: "SDR", symbols: ["XDR"] },
  { code: "AFN", name: "アフガニアフガニ", symbols: ["؋", "AFN"] },
  { code: "IQD", name: "イラクディナール", symbols: ["ع.د", "IQD"] },
  { code: "IRR", name: "イランリアル", symbols: ["﷼", "IRR"] },
  { code: "YER", name: "イエメンリアル", symbols: ["﷼", "YER"] },
  { code: "LBP", name: "レバノンポンド", symbols: ["ل.ل", "LBP"] },
  { code: "SYP", name: "シリアポンド", symbols: ["£S", "SYP"] },
  { code: "SDG", name: "スーダンポンド", symbols: ["SDG"] },
  { code: "SSP", name: "南スーダンポンド", symbols: ["SSP"] },
  { code: "ERN", name: "エリトリアナクファ", symbols: ["Nfk", "ERN"] },
  { code: "DJF", name: "ジブチフラン", symbols: ["Fdj", "DJF"] },
  { code: "SOS", name: "ソマリアシリング", symbols: ["Sh", "SOS"] },
  { code: "RWF", name: "ルワンダフラン", symbols: ["FRw", "RWF"] },
  { code: "BIF", name: "ブルンジフラン", symbols: ["FBu", "BIF"] },
  { code: "CDF", name: "コンゴフラン", symbols: ["FC", "CDF"] },
  { code: "AOA", name: "アンゴラクワンザ", symbols: ["Kz", "AOA"] },
  { code: "SZL", name: "エスワティニリランゲニ", symbols: ["L", "SZL"] },
  { code: "LSL", name: "レソトロチ", symbols: ["L", "LSL"] },
  { code: "MWK", name: "マラウイクワチャ", symbols: ["MK", "MWK"] },
  { code: "ZWL", name: "ジンバブエドル", symbols: ["Z$", "ZWL"] },
  { code: "GMD", name: "ガンビアダラシ", symbols: ["D", "GMD"] },
  { code: "GNF", name: "ギニアフラン", symbols: ["FG", "GNF"] },
  { code: "SLL", name: "シエラレオネレオン", symbols: ["Le", "SLL"] },
  { code: "LRD", name: "リベリアドル", symbols: ["L$", "LRD"] },
  { code: "CVE", name: "カーボベルデエスクード", symbols: ["Esc", "CVE"] },
  { code: "STN", name: "サントメプリンシペドブラ", symbols: ["Db", "STN"] },
  { code: "KMF", name: "コモロフラン", symbols: ["CF", "KMF"] },
  { code: "SCR", name: "セーシェルルピー", symbols: ["₨", "SCR"] },
  { code: "MVR", name: "モルディブルフィヤ", symbols: ["Rf", "MVR"] },
  { code: "BTN", name: "ブータンニュルタム", symbols: ["Nu.", "BTN"] },
  { code: "BND", name: "ブルネイドル", symbols: ["B$", "BND"] },
  { code: "MOP", name: "マカオパタカ", symbols: ["MOP$", "MOP"] },
  { code: "KGS", name: "キルギスソム", symbols: ["с", "KGS"] },
  { code: "TJS", name: "タジキスタンソモニ", symbols: ["SM", "TJS"] },
  { code: "TMT", name: "トルクメニスタンマナト", symbols: ["m", "TMT"] },
  { code: "KPW", name: "北朝鮮ウォン", symbols: ["₩", "KPW"] },
  { code: "CUP", name: "キューバペソ", symbols: ["$MN", "CUP"] },
  { code: "HTG", name: "ハイチグールド", symbols: ["G", "HTG"] },
  { code: "GYD", name: "ガイアナドル", symbols: ["G$", "GYD"] },
  { code: "SRD", name: "スリナムドル", symbols: ["Sr$", "SRD"] },
  { code: "ANG", name: "オランダ領アンティルギルダー", symbols: ["ƒ", "ANG"] },
  { code: "AWG", name: "アルバフロリン", symbols: ["ƒ", "AWG"] },
  { code: "KYD", name: "ケイマン諸島ドル", symbols: ["CI$", "KYD"] },
  { code: "BMD", name: "バミューダドル", symbols: ["BD$", "BMD"] },
  { code: "FKP", name: "フォークランド諸島ポンド", symbols: ["£", "FKP"] },
  { code: "GIP", name: "ジブラルタルポンド", symbols: ["£", "GIP"] },
  { code: "SHP", name: "セントヘレナポンド", symbols: ["£", "SHP"] },
  { code: "IMP", name: "マン島ポンド", symbols: ["£", "IMP"] },
  { code: "JEP", name: "ジャージーポンド", symbols: ["£", "JEP"] },
  { code: "GGP", name: "ガーンジーポンド", symbols: ["£", "GGP"] },
];
